# Generated by Django 5.1.2 on 2025-03-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_Investment_Assistant', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
