# Generated by Django 5.1.2 on 2025-03-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_Investment_Assistant', '0004_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizprogress',
            name='quizzes_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userquizprogress',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
