# Generated by Django 5.1.2 on 2025-03-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_Investment_Assistant', '0005_userquizprogress_quizzes_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizprogress',
            name='answered_questions',
            field=models.JSONField(default=list),
        ),
    ]
