# Generated by Django 5.1.2 on 2025-03-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_Investment_Assistant', '0006_userquizprogress_answered_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='explanation',
        ),
        migrations.RemoveField(
            model_name='userquizprogress',
            name='answered_questions',
        ),
    ]
