# Generated by Django 5.1.2 on 2025-03-11 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_Investment_Assistant', '0008_quizquestion_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquizprogress',
            name='quizzes_completed',
        ),
        migrations.RemoveField(
            model_name='userquizprogress',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='userquizprogress',
            name='xp_points',
        ),
        migrations.AddField(
            model_name='userquizprogress',
            name='xp_per_quiz',
            field=models.JSONField(default=dict),
        ),
    ]
