# Generated by Django 5.1.2 on 2025-03-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_Investment_Assistant', '0009_remove_userquizprogress_quizzes_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizprogress',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
