# Generated by Django 5.1.2 on 2025-03-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_Investment_Assistant', '0010_userquizprogress_total_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='explanation',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
