# Generated by Django 5.1.2 on 2025-03-11 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_Investment_Assistant', '0011_alter_quizquestion_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizprogress',
            name='last_xp_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
