# Generated by Django 5.1.2 on 2025-04-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_Investment_Assistant', '0013_watchedstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatIfTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('plotly_json', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
