# Generated by Django 5.1.2 on 2025-04-26 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_Investment_Assistant', '0014_whatiftaskresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatiftaskresult',
            name='plotly_json',
        ),
    ]
