# Generated by Django 5.1.2 on 2025-04-27 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_Investment_Assistant', '0015_remove_whatiftaskresult_plotly_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatiftaskresult',
            name='notification_sent',
            field=models.BooleanField(default=False),
        ),
    ]
