# Generated by Django 5.1.2 on 2025-04-27 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_Investment_Assistant', '0016_whatiftaskresult_notification_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatiftaskresult',
            name='notification_sent',
        ),
    ]
