# Generated by Django 5.1.2 on 2025-04-27 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_Investment_Assistant', '0018_portfolio_holding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='user',
        ),
        migrations.DeleteModel(
            name='Holding',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
